# Generated by Django 3.2 on 2021-04-30 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='Адрес')),
                ('purpose', models.CharField(blank=True, max_length=20, verbose_name='Назначение')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('quality', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='Категория')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.type', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_quality', models.IntegerField(default=0, verbose_name='Количество')),
                ('income_note', models.CharField(blank=True, max_length=50, verbose_name='Примечание')),
                ('income_date_create', models.DateTimeField(auto_now_add=True)),
                ('income_date_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='Категория')),
                ('income_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product', verbose_name='Название')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.type', verbose_name='Тип')),
                ('income_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_quality', models.IntegerField(default=0, verbose_name='Количество')),
                ('expense_note', models.CharField(blank=True, max_length=50, verbose_name='Примечание')),
                ('expense_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.object', verbose_name='Адрес')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='Категория')),
                ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product', verbose_name='Название')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.type', verbose_name='Тип')),
                ('expense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
