# Generated by Django 3.2.4 on 2022-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20220302_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_date_update',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
