# Generated by Django 3.2 on 2021-04-16 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(max_length=4, unique=True, verbose_name='Vlan')),
                ('vlan_client', models.CharField(blank=True, max_length=30, verbose_name='Заказчик')),
                ('vlan_order', models.CharField(blank=True, max_length=10, verbose_name='Номер заказа')),
                ('vlan_used_for', models.CharField(blank=True, max_length=50, verbose_name='Назначение')),
                ('vlan_point_a', models.CharField(blank=True, max_length=20, verbose_name='Точка А')),
                ('vlan_point_b', models.CharField(blank=True, max_length=20, verbose_name='Точка Б')),
                ('vlan_speed', models.IntegerField(default=0, verbose_name='Скорость (Mbps)')),
                ('vlan_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('vlan_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('vlan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_order', models.IntegerField(unique=True, verbose_name='Номер')),
                ('switch_address', models.CharField(blank=True, max_length=20, verbose_name='Адрес')),
                ('switch_ip', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('switch_mac', models.CharField(max_length=50, unique=True, verbose_name='MAC')),
                ('switch_model', models.CharField(blank=True, max_length=20, verbose_name='Модель')),
                ('switch_firmware', models.CharField(blank=True, max_length=20, verbose_name='Прошивка')),
                ('switch_serial', models.CharField(max_length=20, unique=True, verbose_name='Серийный номер')),
                ('switch_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('switch_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('switch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
