# Generated by Django 3.2.4 on 2022-04-18 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True, verbose_name='Номер')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('mac', models.CharField(max_length=17, unique=True, verbose_name='MAC')),
                ('model', models.CharField(blank=True, max_length=20, verbose_name='Модель')),
                ('firmware', models.CharField(blank=True, max_length=20, verbose_name='Прошивка')),
                ('serial', models.CharField(max_length=20, unique=True, verbose_name='Серийный номер')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(max_length=4, unique=True, verbose_name='Vlan')),
                ('vlan_client', models.CharField(blank=True, max_length=30, verbose_name='Заказчик')),
                ('vlan_order', models.CharField(blank=True, max_length=10, verbose_name='Номер заказа')),
                ('vlan_used_for', models.CharField(blank=True, max_length=50, verbose_name='Назначение')),
                ('vlan_point_a', models.CharField(blank=True, max_length=20, verbose_name='Точка А')),
                ('vlan_point_b', models.CharField(blank=True, max_length=20, verbose_name='Точка Б')),
                ('vlan_speed', models.IntegerField(default=0, verbose_name='Скорость (Mbps)')),
                ('vlan_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('vlan_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('vlan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_client', models.CharField(blank=True, max_length=30, verbose_name='Заказчик')),
                ('vlan_order', models.CharField(blank=True, max_length=10, verbose_name='Номер заказа')),
                ('vlan_used_for', models.CharField(blank=True, max_length=50, verbose_name='Назначение')),
                ('vlan_point_a', models.CharField(blank=True, max_length=20, verbose_name='Точка А')),
                ('vlan_point_b', models.CharField(blank=True, max_length=20, verbose_name='Точка Б')),
                ('vlan_speed', models.IntegerField(default=0, verbose_name='Скорость (Mbps)')),
                ('vlan_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('vlan_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('vlan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.vlan', verbose_name='Vlan')),
                ('vlan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-vlan_time'],
            },
        ),
        migrations.CreateModel(
            name='SwitchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('mac', models.CharField(max_length=17, unique=True, verbose_name='MAC')),
                ('model', models.CharField(blank=True, max_length=30, verbose_name='Модель')),
                ('firmware', models.CharField(blank=True, max_length=30, verbose_name='Прошивка')),
                ('serial', models.CharField(max_length=30, verbose_name='Серийный номер')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date', models.DateTimeField(verbose_name='Дата изменения')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.switch', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
