# Generated by Django 3.2.4 on 2022-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchhistory',
            name='order',
            field=models.CharField(max_length=255, verbose_name='Номер'),
        ),
    ]
