# Generated by Django 3.2.4 on 2022-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_switchhistory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchhistory',
            name='mac',
            field=models.CharField(max_length=17, verbose_name='MAC'),
        ),
    ]
