# Generated by Django 3.2 on 2021-04-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_switchhistory_vlanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchhistory',
            name='switch_ip',
            field=models.CharField(max_length=15, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='switchhistory',
            name='switch_mac',
            field=models.CharField(max_length=50, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='switchhistory',
            name='switch_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.switch', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='switchhistory',
            name='switch_serial',
            field=models.CharField(max_length=20, verbose_name='Серийный номер'),
        ),
    ]
