# Generated by Django 3.2 on 2021-04-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210419_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='switchhistory',
            options={'ordering': ['-switch_time']},
        ),
        migrations.AlterModelOptions(
            name='vlan',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='vlanhistory',
            name='vlan_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.vlan', verbose_name='Vlan'),
        ),
    ]
