# Generated by Django 3.2.4 on 2022-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_switchhistory_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchhistory',
            name='user',
            field=models.CharField(max_length=30, verbose_name='Изменил'),
        ),
    ]
