# Generated by Django 3.2 on 2021-04-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210419_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlanhistory',
            options={'ordering': ['-vlan_time']},
        ),
    ]
