# Generated by Django 3.2.4 on 2022-04-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20220407_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='time',
            new_name='date',
        ),
    ]
