# Generated by Django 3.2.4 on 2022-02-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addressbook', '0001_initial'),
        ('storage', '0002_auto_20211202_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Нет кабеля', 'Нет кабеля'), ('Необходима сварка', 'Необходима сварка'), ('Готов к подключению', 'Готов к подключению')], default='Нет кабеля', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addressbook.address', verbose_name='Адрес')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тарифа')),
                ('speed', models.IntegerField(default='100', verbose_name='Скорость Мбит/с')),
                ('price', models.IntegerField(verbose_name='Стоимость тарифа')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('date_req', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
                ('date_con', models.DateTimeField(blank=True, null=True, verbose_name='Дата подключения')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('price_con', models.PositiveIntegerField(default=0, verbose_name='Цена подключения')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpon.house', verbose_name='Адрес')),
                ('cord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cord', to='storage.product', verbose_name='Патч-корд')),
                ('installer', models.ManyToManyField(blank=True, related_name='installer', to=settings.AUTH_USER_MODEL, verbose_name='Монтажники')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ont', to='storage.product', verbose_name='Модель ONT')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router', to='storage.product', verbose_name='Модель Wi-Fi роутера')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpon.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
