# Generated by Django 3.2.4 on 2022-01-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20211202_1533'),
        ('gpon', '0004_alter_request_installer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ont', to='storage.product', verbose_name='Модель ONT'),
        ),
        migrations.AlterField(
            model_name='request',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router', to='storage.product', verbose_name='Модель Wi-Fi роутера'),
        ),
    ]
