# Generated by Django 3.2.4 on 2022-02-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0005_auto_20220131_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ont',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
