# Generated by Django 3.2.4 on 2022-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0005_rename_active_tariff_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='price_con',
        ),
        migrations.AddField(
            model_name='request',
            name='cost_con',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость подключения'),
        ),
        migrations.AddField(
            model_name='request',
            name='router_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость роутера'),
        ),
        migrations.AddField(
            model_name='request',
            name='tariff_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость тарифа'),
        ),
    ]
