# Generated by Django 3.2.4 on 2022-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0006_auto_20220201_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
    ]
