# Generated by Django 3.2.4 on 2022-02-10 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpon', '0010_auto_20220209_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['address']},
        ),
        migrations.RemoveField(
            model_name='house',
            name='area',
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
