# Generated by Django 3.2.4 on 2022-02-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0011_auto_20220210_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='gpon.house', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='request',
            name='price_con',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена подключения'),
        ),
    ]
