# Generated by Django 3.2.4 on 2022-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0012_auto_20220211_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='price_con',
            field=models.IntegerField(default=0, verbose_name='Цена подключения'),
        ),
    ]
