# Generated by Django 3.2.4 on 2022-02-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0013_alter_request_price_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='price_con',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена подключения'),
        ),
    ]
