# Generated by Django 3.2.4 on 2022-02-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0014_alter_request_price_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpon.house', verbose_name='Адрес'),
        ),
    ]
