# Generated by Django 3.2.4 on 2022-02-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20211202_1533'),
        ('gpon', '0015_alter_request_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_req',
            new_name='date_reg',
        ),
        migrations.AddField(
            model_name='request',
            name='cord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cord', to='storage.product', verbose_name='Патч-корд'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
