# Generated by Django 3.2.4 on 2022-02-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpon', '0016_auto_20220216_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_reg',
            new_name='date_req',
        ),
    ]
