# Generated by Django 3.2.4 on 2022-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('проспект', 'проспект'), ('улица', 'улица'), ('бульвар', 'бульвар'), ('проезд', 'проезд'), ('переулок', 'переулок'), ('шоссе', 'шоссе')], default='улица', max_length=10, verbose_name='Тип')),
                ('address_name', models.CharField(max_length=50, verbose_name='Название')),
                ('address_house', models.CharField(max_length=5, verbose_name='Номер дома')),
            ],
            options={
                'ordering': ['address_type', 'address_name', 'address_house'],
                'unique_together': {('address_type', 'address_name', 'address_house')},
            },
        ),
    ]
