# Generated by Django 3.2.4 on 2021-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('проспект', 'проспект'), ('улица', 'улица'), ('бульвар', 'бульвар'), ('проезд', 'проезд'), ('переулок', 'переулок'), ('шоссе', 'шоссе')], max_length=10, verbose_name='Тип')),
                ('address_name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('address_house', models.CharField(max_length=5, unique=True, verbose_name='Номер дома')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
    ]
