# Generated by Django 3.2.4 on 2021-12-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_remove_address_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_house',
            field=models.CharField(max_length=5, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
