# Generated by Django 3.2.4 on 2022-02-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_auto_20211224_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['address_type', 'address_name', 'address_house']},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('проспект', 'проспект'), ('улица', 'улица'), ('бульвар', 'бульвар'), ('проезд', 'проезд'), ('переулок', 'переулок'), ('шоссе', 'шоссе')], default='улица', max_length=10, verbose_name='Тип'),
        ),
    ]
